### PR TITLE
Show fullscreen

### PR DESCRIPTION
**Pull request by btj**
This is necessary to see the text at the bottom on my MacBook Pro.

### CODE REVIEW

**Comment by gera2342** [comment]
That causes my screen blink a few times on linux when my resolution doesnt match `SCREEN_` constants. Does it work for you with `SDL_WINDOW_RESIZABLE`?

**Comment by btj** [comment]
> Does it work for you with `SDL_WINDOW_RESIZABLE`?

No; the game simply does not fit on the screen. A solution would be to draw the text higher; there's a lot of seemingly useless blank space between the space view and the text.

**Comment by mohd-akram** [comment]
`SDL_WINDOW_RESIZABLE` works when combined with `SDL_RenderSetLogicalSize(renderer, SCREEN_WIDTH, SCREEN_HEIGHT)`, but it doesn't restrict aspect ratio when resizing so the lines can disappear. Fullscreen is neat but the game should be playable in windowed mode too. Still haven't figured out a good solution.

**Comment by larsbrinkhoff** [comment]
Here is code I added to SIMH for toggling full screen mode:  
https://github.com/open-simh/simh/commit/d93bfe62dea0374ed2c5aa3d3040e590341cdbbf

Scaling is achieved by rendering to an off-screen texture and rendering that onto the window:  
https://github.com/open-simh/simh/commit/6ca7a938ad99261dd44cf6696af79ae35c588817

**Comment by mohd-akram** [comment]
I've pushed a change to allow resizing, try it out and see if it works for you.

**Comment by btj** [comment]
Yes; now I can see the text! Closing the PR.

**Pull request closed without merging**
