### PR TITLE
Add support for WebAssembly/emscripten

### PR DESCRIPTION
**Pull request by ko1nksm**
This PR adds support for building WebAssembly (with emscripten).

```sh
# Build with emscripten
emcc st.c -s USE_SDL=2 -o st.html
```

Start the web server and access it with a browser.

```console
$ python3 -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
```

### CODE REVIEW

**Comment by ko1nksm** [comment]
Are you interested in publishing Space Travel on GitHub Pages? If interested I will create a PR for it. It will be easy for everyone to play with Space Travel.

**Comment by mohd-akram** [comment]
Thanks.

> Are you interested in publishing Space Travel on GitHub Pages? If interested I will create a PR for it. It will be easy for everyone to play with Space Travel.

Yeah, this would be great.

**Comment by ko1nksm** [comment]
OK, I will prepare. Thanks for resurrecting Space Travel!

**Comment by larsbrinkhoff** [comment]
Agreed.  Thanks again, @mohd-akram.  But also note that @philbudne and @sebras deserves some credit.

**Comment by philbudne** [comment]
Well, I did the display framework that the SimH implementation of G2 used,
so VERY indirectly (this program doesn't simulate phosphor persistence),
and I owe credit to @douglas-w-jones for my start on that!!



Is there a URL where the emscriptenified code can be run?

**Comment by ko1nksm** [comment]
Hi @philbudne.

Space Travel is currently running temporarily at https://ko1nksm.github.io/st/ . (See. #10)

The emscriptenified code can be downloaded from the following URL

- https://ko1nksm.github.io/st/st.wasm
- https://ko1nksm.github.io/st/st.js
- https://ko1nksm.github.io/st/index.html

**Comment by mohd-akram** [comment]
Thanks @ko1nksm! I've merged the PR and you can access the game at https://akr.am/st now.

**Pull request merged**
